[versions]
agp = "8.12.0"
kotlin = "2.2.10"
coreKtx = "1.17.0"
activityCompose = "1.10.1"
composeBom = "2025.08.00"
koinBom = "4.1.0"
ktor = "3.2.3"
coil = "3.3.0"
navigation = "2.9.3"
prefs = "1.2.1"
googleServices = "4.4.3"
firebaseBom = "34.1.0"
datetime = "0.7.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

androidx-preferences = { group = "androidx.preference", name = "preference", version.ref = "prefs" }
androidx-preferences-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "prefs" }

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }

androidx-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }

androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-foundation = { group = "androidx.compose.foundation", name = "foundation" }

io-insert-koin-koin-bom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koinBom" }
io-insert-koin-koin-core = { group = "io.insert-koin", name = "koin-core" }
io-insert-koin-koin-compose = { group = "io.insert-koin", name = "koin-compose" }
io-insert-koin-koin-android = { group = "io.insert-koin", name = "koin-android" }
io-insert-koin-koin-androidx-compose = { group = "io.insert-koin", name = "koin-androidx-compose" }
io-insert-koin-koin-androidx-workmanager = { group = "io.insert-koin", name = "koin-androidx-workmanager" }

io-ktor-ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
io-ktor-ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
io-ktor-ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
io-ktor-ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }

io-coil-kt-coil3-coil-bom = { group = "io.coil-kt.coil3", name = "coil-bom", version.ref = "coil" }
io-coil-kt-coil3-coil-core = { group = "io.coil-kt.coil3", name = "coil-core" }
io-coil-kt-coil3-coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose" }
io-coil-kt-coil3-coil-network-okhttp = { group = "io.coil-kt.coil3", name = "coil-network-okhttp" }
io-coil-kt-coil3-coil-network-ktor3 = { group = "io.coil-kt.coil3", name = "coil-network-ktor3" }

kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "datetime" }

firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-fcm = { group = "com.google.firebase", name = "firebase-messaging" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
